theme: jekyll-theme-slate
# --- Basic options --- #

# Name of website
title: David Pearce

# Short description of your site
description: Personal Blog

# Your name to show in the footer
author: David Pearce

#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
